# Site settings
title: Pieter Vallen's IT blog (beta)
email: Pieter@Vallen.net
description: > # this means to ignore newlines until "baseurl:"
   On this site I write about stuff that interest me. It (will)
   contain mostly short howto's in the beginning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pietervallen.github.io" # the base hostname & protocol for your site
twitter_username: pietervallen
github_username:  pietervallen

# Build settings
markdown: kramdown
